### ISSUE TITLE
Add table scaleway_baremetal_server

### ISSUE THREAD

**Issue by FalcoXYZ** [turbot/steampipe-plugin-scaleway#16]
Currently, it's only possible to query scaleway_instance_server and not the baremetal end of Scaleway. Would be nice if this was possible. I added relevant links as reference, also instance_server to compare it to the baremetal one. 

**References**
https://github.com/scaleway/scaleway-sdk-go/blob/master/api/baremetal/v1/baremetal_sdk.go
https://github.com/scaleway/scaleway-sdk-go/blob/master/api/instance/v1/instance_sdk.go

**Comment by cbruno10** [comment]
Thanks for opening this issue @FalcoXYZ !

If anyone is interested in trying to add this new table, the links @FalcoXYZ included above are great starting points. We're happy to answer any questions and provide help along the way too.

**Comment by jplanckeel** [comment]
Hello, i have create a [pull request](https://github.com/turbot/steampipe-plugin-scaleway/pull/17) to add this table. i need a person to test this. I don't have for the moment an account with bare metal :/

**Comment by e-gineer** [comment]
@FalcoXYZ Would you be able to collaborate with / test for @jplanckeel?

**Comment by jplanckeel** [comment]
We can close this issue because thsi PR is merged ;) https://github.com/turbot/steampipe-plugin-scaleway/pull/17

**Comment by cbruno10** [comment]
Thanks again @jplanckeel for the PR! Closing the issue.
